-- VHDL Entity ece411.MDRL.generatedInstance
--
-- Created:
--          by - jconroy2.stdt (gllnx36.ews.illinois.edu)
--          at - 00:57:38 09/17/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.NUMERIC_STD.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;
USE ieee.std_logic_arith.all;

ENTITY MDRL IS
   PORT( 
      MDRout  : IN     lc3b_word;
      MDRLout : OUT    lc3b_word;
      clk     : IN     std_logic
   );

END MDRL ;

-- 
-- Auto generated dummy architecture for leaf level instance.
-- 
ARCHITECTURE generatedInstance OF MDRL IS 
BEGIN


END generatedInstance;
