-- VHDL Entity ece411.WAY.symbol
--
-- Created:
--          by - jconroy2.stdt (eelnx39.ews.illinois.edu)
--          at - 20:57:46 10/18/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WAY IS
   PORT( 
      ADDRTAG      : IN     lc3b_tag;
      ADDRindex    : IN     lc3b_cacheindex;
      RESET_L      : IN     std_logic;
      WAY_DATAIN   : IN     LC3b_oword;
      WAY_dirtyIn  : IN     std_logic;
      WAY_validIn  : IN     std_logic;
      WAY_write    : IN     std_logic;
      clk          : IN     std_logic;
      WAY_DATA     : OUT    LC3b_oword;
      WAY_TAG      : OUT    lc3b_TAG;
      WAY_dirtyOut : OUT    std_logic;
      WAY_valid    : OUT    std_logic
   );

-- Declarations

END WAY ;

--
-- VHDL Architecture ece411.WAY.struct
--
-- Created:
--          by - jconroy2.stdt (eelnx39.ews.illinois.edu)
--          at - 20:57:47 10/18/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF WAY IS

   -- Architecture declarations

   -- Internal signal declarations


   -- Component Declarations
   COMPONENT DataArray
   PORT (
      ADDRindex  : IN     lc3b_cacheindex ;
      RESET_L    : IN     std_logic ;
      WAY_DATAIN : IN     LC3b_oword ;
      WAY_write  : IN     std_logic ;
      clk        : IN     std_logic ;
      WAY_DATA   : OUT    LC3b_oword 
   );
   END COMPONENT;
   COMPONENT TAGArray
   PORT (
      ADDRTAG   : IN     lc3b_tag ;
      ADDRindex : IN     lc3b_cacheindex ;
      RESET_L   : IN     std_logic ;
      WAY_write : IN     std_logic ;
      clk       : IN     std_logic ;
      WAY_TAG   : OUT    lc3b_TAG 
   );
   END COMPONENT;
   COMPONENT dirtyArray
   PORT (
      ADDRindex    : IN     lc3b_cacheindex ;
      RESET_L      : IN     std_logic ;
      WAY_dirtyIn  : IN     std_logic ;
      WAY_write    : IN     std_logic ;
      clk          : IN     std_logic ;
      WAY_dirtyOut : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT validArray
   PORT (
      ADDRindex   : IN     lc3b_cacheindex ;
      RESET_L     : IN     std_logic ;
      WAY_validIn : IN     std_logic ;
      WAY_write   : IN     std_logic ;
      clk         : IN     std_logic ;
      WAY_valid   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : DataArray USE ENTITY ece411.DataArray;
   FOR ALL : TAGArray USE ENTITY ece411.TAGArray;
   FOR ALL : dirtyArray USE ENTITY ece411.dirtyArray;
   FOR ALL : validArray USE ENTITY ece411.validArray;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   aDataArray : DataArray
      PORT MAP (
         ADDRindex  => ADDRindex,
         RESET_L    => RESET_L,
         WAY_DATAIN => WAY_DATAIN,
         WAY_write  => WAY_write,
         clk        => clk,
         WAY_DATA   => WAY_DATA
      );
   aTAGArray : TAGArray
      PORT MAP (
         ADDRTAG   => ADDRTAG,
         ADDRindex => ADDRindex,
         RESET_L   => RESET_L,
         WAY_write => WAY_write,
         clk       => clk,
         WAY_TAG   => WAY_TAG
      );
   adirtyArray : dirtyArray
      PORT MAP (
         ADDRindex    => ADDRindex,
         RESET_L      => RESET_L,
         WAY_dirtyIn  => WAY_dirtyIn,
         WAY_write    => WAY_write,
         clk          => clk,
         WAY_dirtyOut => WAY_dirtyOut
      );
   avalidArray : validArray
      PORT MAP (
         ADDRindex   => ADDRindex,
         RESET_L     => RESET_L,
         WAY_validIn => WAY_validIn,
         WAY_write   => WAY_write,
         clk         => clk,
         WAY_valid   => WAY_valid
      );

END struct;
