-- VHDL Entity ece411.WT.symbol
--
-- Created:
--          by - jconroy2.stdt (eelnx39.ews.illinois.edu)
--          at - 20:57:46 10/18/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

ENTITY WT IS
   PORT( 
      LineData : IN     LC3B_word;
      MWH      : IN     std_logic;
      MWL      : IN     std_logic;
      Sel      : IN     std_logic;
      dataout  : IN     LC3B_word;
      WTout    : OUT    LC3B_word
   );

-- Declarations

END WT ;

--
-- VHDL Architecture ece411.WT.struct
--
-- Created:
--          by - jconroy2.stdt (eelnx39.ews.illinois.edu)
--          at - 20:57:46 10/18/10
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2005.3 (Build 75)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY ece411;
USE ece411.LC3b_types.all;

LIBRARY ece411;

ARCHITECTURE struct OF WT IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL F                : std_logic;
   SIGNAL F1               : std_logic;
   SIGNAL LinebyteH        : LC3B_byte;
   SIGNAL LinebyteL        : LC3B_byte;
   SIGNAL MWH_H            : std_logic;
   SIGNAL MWH_L            : std_logic;
   SIGNAL WriteCombMuxHout : LC3B_byte;
   SIGNAL WriteCombMuxLout : LC3B_byte;
   SIGNAL dataoutbyteH     : LC3B_byte;
   SIGNAL dataoutbyteL     : LC3B_byte;


   -- Component Declarations
   COMPONENT ByteMux2
   PORT (
      A   : IN     lc3b_byte ;
      B   : IN     lc3b_byte ;
      sel : IN     std_logic ;
      F   : OUT    LC3B_byte 
   );
   END COMPONENT;
   COMPONENT LC3_NAND
   PORT (
      A : IN     std_logic ;
      B : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT LC3_NOT
   PORT (
      A : IN     std_logic ;
      F : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT WordSplit
   PORT (
      Word  : IN     LC3B_word ;
      byteH : OUT    LC3B_byte ;
      byteL : OUT    LC3B_byte 
   );
   END COMPONENT;
   COMPONENT byte_comb
   PORT (
      WriteCombMuxHout : IN     LC3B_byte ;
      WriteCombMuxLout : IN     LC3B_byte ;
      WTout            : OUT    LC3B_word 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ByteMux2 USE ENTITY ece411.ByteMux2;
   FOR ALL : LC3_NAND USE ENTITY ece411.LC3_NAND;
   FOR ALL : LC3_NOT USE ENTITY ece411.LC3_NOT;
   FOR ALL : WordSplit USE ENTITY ece411.WordSplit;
   FOR ALL : byte_comb USE ENTITY ece411.byte_comb;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   WriteCombMuxH : ByteMux2
      PORT MAP (
         A   => dataoutbyteH,
         B   => LinebyteH,
         sel => F,
         F   => WriteCombMuxHout
      );
   WriteCombMuxL : ByteMux2
      PORT MAP (
         A   => dataoutbyteL,
         B   => LinebyteL,
         sel => F1,
         F   => WriteCombMuxLout
      );
   LineHNAND : LC3_NAND
      PORT MAP (
         A => Sel,
         B => MWH_H,
         F => F
      );
   LineLNAND : LC3_NAND
      PORT MAP (
         A => Sel,
         B => MWH_L,
         F => F1
      );
   U_0 : LC3_NOT
      PORT MAP (
         A => MWH,
         F => MWH_H
      );
   U_1 : LC3_NOT
      PORT MAP (
         A => MWL,
         F => MWH_L
      );
   DataOutSplit : WordSplit
      PORT MAP (
         Word  => dataout,
         byteH => dataoutbyteH,
         byteL => dataoutbyteL
      );
   LineDataSplit : WordSplit
      PORT MAP (
         Word  => LineData,
         byteH => LinebyteH,
         byteL => LinebyteL
      );
   aByte_Comb : byte_comb
      PORT MAP (
         WriteCombMuxHout => WriteCombMuxHout,
         WriteCombMuxLout => WriteCombMuxLout,
         WTout            => WTout
      );

END struct;
